[package]
name = "variables"
version = "0.1.0"
authors = ["Louxi3152 <34438507+Louxi3152@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
